name: Building scu

on:

  push:

    branches: [ master ]

  pull_request:

    branches: [ master ]

jobs:
  build-scu:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2 
      with:
          vs-version: 15.0
    
    #- name: subscribe1 build
     # run: msbuild scu.vcxproj /p:configuration=debug /p:platform=x64
 
    - name: msbuild Project build
      run:  msbuild .\SenderTest1\TransferMedicalimages.vcxproj /p:configuration=debug /p:platform=x64
      
    - name: build senderTestApplication
      run: g++ -S SenderTest1\*.cpp --coverage
    
    - name: move gcno to sender test dir
      run: move *.gcno SenderTest1 

    - name: move senderTestApp to mc3lib
      run: copy SenderTest\x64\debug\TransferMedicalimages.exe  .\mc3lib\
    
    - name: cd into mc3lib to run sender
      run: cd mc3lib && ./TransferMedicalimages.exe 

    - name: move .gcda files to sender test dir
      run:  move *.gcda SenderTest1

    - name: sender coverage report
      run:  gcov -r SenderTest1/ImageList.cpp
    - name: sender coverage report
      run : gcov -r SenderTest1/ImageListTest.cpp
    - name: sender coverage report
      run : gcov -r SenderTest1/ReadMessageFromFile.cpp
    - name: sender coverage report
      run : gcov -r SenderTest1/SendImage.cpp
    - name: sender coverage report
      run : gcov -r SenderTest1/SenderMainFunctions.cpp
    - name: sender coverage report
      run : gcov -r SenderTest1/general_util.cpp
